name: Deploy to VM

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Версия Docker-образа для деплоя (например, 9_latest)"
        required: true

jobs:
  deploy:
    name: Deploy to Yandex Cloud VM
    runs-on: ubuntu-latest
    env:
      REGISTRY: cr.yandex/crpfnnn98v057d07iqev
      IMAGE_NAME: app
      RELEASE_VERSION: ${{ github.event.inputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_IP }}
          username: dinara
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "REGISTRY: cr.yandex/crpfnnn98v057d07iqev"
            echo "IMAGE_NAME: app"
            echo "RELEASE_VERSION: ${{ github.event.inputs.version }}"
            echo "IMAGE TO RUN: cr.yandex/crpfnnn98v057d07iqev/app:${{ github.event.inputs.version }}"
            docker login -u oauth -p ${{ secrets.Y_CR_TOKEN }} cr.yandex
            docker pull cr.yandex/crpfnnn98v057d07iqev/app:${{ github.event.inputs.version }}
            docker stop shri-infra || true
            docker rm shri-infra || true
            docker run -d --name shri-infra -p 3000:3000 cr.yandex/crpfnnn98v057d07iqev/app:${{ github.event.inputs.version }}

      - name: Extract base release version
        id: base_version
        run: |
          BASE_VERSION=$(echo "${{ github.event.inputs.version }}" | sed 's/_.*//')
          echo "BASE_VERSION=$BASE_VERSION" >> $GITHUB_OUTPUT

      - name: Find release issue number
        id: find_issue
        run: |
          ISSUE_NUMBER=$(gh issue list --state open --search "Release ${{ steps.base_version.outputs.BASE_VERSION }} in:title" --json number -q '.[0].number')
          echo "ISSUE_NUMBER=$ISSUE_NUMBER" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add comment to release issue
        if: ${{ steps.find_issue.outputs.ISSUE_NUMBER != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue comment ${{ steps.find_issue.outputs.ISSUE_NUMBER }} \
            --body "Деплой версии ${{ github.event.inputs.version }} в прод  
            Дата: $(date '+%Y-%m-%d %H:%M:%S')  
            Автор: ${{ github.actor }}  

            Docker-образ: cr.yandex/crpfnnn98v057d07iqev/app:${{ github.event.inputs.version }}"

      - name: Debug Issue not found
        if: ${{ steps.find_issue.outputs.ISSUE_NUMBER == '' }}
        run: |
          echo "Релизный Issue для Release ${{ steps.base_version.outputs.BASE_VERSION }} не найден. Комментарий не добавлен."
