name: start release flow

on:
  workflow_dispatch:

jobs:
  release:
    name: Release build and publish
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [20.x]
        os: [ubuntu-latest]
    env:
      REGISTRY: cr.yandex/${{ secrets.YC_CR_REGISTRY_ID }}
      IMAGE_NAME: app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run tests
        run: npm run test

      - name: Get release version
        id: version
        run: echo "RELEASE_VERSION=${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login to Yandex Cloud Container Registry
        run: echo ${{ secrets.Y_CR_TOKEN }} | docker login --username oauth --password-stdin cr.yandex

      - name: Build Docker image
        run: |
          docker build -t $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }} .
          docker tag $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }} $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }}_latest

      - name: Push Docker images
        run: |
          docker push $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }}
          docker push $REGISTRY/$IMAGE_NAME:${{ env.RELEASE_VERSION }}_latest

      - name: Create release branch
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b releases/${{ env.RELEASE_VERSION }}
          git push origin releases/${{ env.RELEASE_VERSION }}

      - name: Get previous tag
        id: prev_tag
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          echo "PREV_TAG=$PREV_TAG" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git tag v${{ env.RELEASE_VERSION }}
          git push origin v${{ env.RELEASE_VERSION }}

      - name: Generate commit list
        id: commits
        run: |
          if [ -z "${{ env.PREV_TAG }}" ]; then
            COMMITS=$(git log --pretty=format:"- %s (%h)" HEAD)
          else
            COMMITS=$(git log ${{ env.PREV_TAG }}..HEAD --pretty=format:"- %s (%h)")
          fi
          echo "COMMITS<<EOF" >> $GITHUB_ENV
          echo "$COMMITS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Update CHANGELOG.md
        run: |
          echo "# v${{ env.RELEASE_VERSION }} $(date +'%Y-%m-%d')" > new_changelog.md
          echo "" >> new_changelog.md
          echo "${{ env.COMMITS }}" >> new_changelog.md
          echo "" >> new_changelog.md
          cat CHANGELOG.md >> new_changelog.md
          mv new_changelog.md CHANGELOG.md

          git add CHANGELOG.md
          git commit -m "Update CHANGELOG for v${{ env.RELEASE_VERSION }}"
          git push origin releases/${{ env.RELEASE_VERSION }}

      - name: Сформировать тело Issue релиза
        run: |
          echo "# Релиз ${{ env.RELEASE_VERSION }}" > issue_body.txt
          echo "" >> issue_body.txt
          echo "**Дата:** $(date '+%Y-%m-%d %H:%M:%S')" >> issue_body.txt
          echo "**Автор релиза:** ${{ github.actor }}" >> issue_body.txt
          echo "**Номер версии:** ${{ env.RELEASE_VERSION }}" >> issue_body.txt
          echo "" >> issue_body.txt
          echo "**Список коммитов с предыдущего релиза:**" >> issue_body.txt
          echo "${{ env.COMMITS }}" >> issue_body.txt
          echo "" >> issue_body.txt
          echo "**Docker-образ:** cr.yandex/${{ secrets.YC_CR_REGISTRY_ID }}/app:${{ env.RELEASE_VERSION }}" >> issue_body.txt

      - name: Создать Issue в GitHub
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Release ${{ env.RELEASE_VERSION }}"
          content-filepath: ./issue_body.txt
